apiVersion: apps/v1
kind: Deployment
metadata:
  name: config
spec:
  #replicas: 3
  selector:
    matchLabels:
      app: config
  template:
    metadata:
      labels:
        app: config
    spec:
      containers:
      - name: spring-cloud-config
        image: manuexcd/spring-cloud-config
        resources:
          requests:
            cpu: "0.1"
        ports:
        - containerPort: 8081
---
kind: Service
apiVersion: v1
metadata:
  name: config
spec:
  type: LoadBalancer
  selector:
    app: config
  ports:
    - port: 8081
      targetPort: 8081