apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
  labels:
    name: discovery
spec:
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
      - name: gateway
        image: manuexcd/spring-cloud-gateway
        resources:
          requests:
            cpu: "0.01"
          limits:
            cpu: "0.4"
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: kubernetes
---
kind: Service
apiVersion: v1
metadata:
  name: gateway
spec:
  type: NodePort
  selector:
    app: gateway
  ports:
    - port: 8080
      targetPort: 8080