apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: jenkins
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      containers:
      - name: jenkins
        image: jenkins/jenkins
        resources:
          requests:
            cpu: "0.05"
          limits:
            cpu: "0.2"
        ports:
        - containerPort: 8080
          name: jenkins
        volumeMounts:
          - mountPath: /var/jenkins_home
            name: jenkins-home
        resources:
          limits:
            cpu: 500m
            memory: 1500Mi
          requests:
            cpu: 500m
            memory: 1500Mi
      volumes:
      - name: jenkins-home
        gcePersistentDisk:
          pdName: jenkins-home
          fsType: ext4
          partition: 1
---
kind: Service
apiVersion: v1
metadata:
  name: jenkins
spec:
  type: LoadBalancer
  selector:
    app: jenkins
  ports:
    - port: 80
      targetPort: 8080