apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: jenkins
spec:
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      containers:
      - name: jenkins
        image: jenkins/jenkins
        resources:
          requests:
            cpu: "0.05"
          limits:
            cpu: "0.2"
        ports:
        - containerPort: 8088
          name: jenkins
---
kind: Service
apiVersion: v1
metadata:
  name: jenkins
spec:
  type: LoadBalancer
  selector:
    app: jenkins
  ports:
    - port: 8088
      targetPort: 8088